# @package _global_

fps: 25

calibration:
  axis_directions: [-1, 1, 1, 1, 1, 1]
  offsets: [0, 0, 0, 0, 0, 0]

state_keys: {"observation.state": "agent_pos", "observation.environment_state": "environment_state"}

env:
  name: so100
  task: PushCube-v0
  image_size: 96
  state_dim: 6 #6(pos)
  action_dim: 6 #6(new pos)
  fps: ${fps}
  episode_length: 100
  gym:
    observation_mode: state
    render_mode: human
    curriculum_level: 0
