# @package _global_

fps: 10

env:
  name: so100
  task: PushCube-v0
  image_size: 96
  state_dim: 6 #6(pos)
  action_dim: 6 #6(new pos)
  fps: ${fps}
  episode_length: 300
  gym:
    observation_mode: state
    render_mode: rgb_array